##config db 14.225.198.8
server.db.ip=localhost
server.db.port=3306
server.db.name=hashirama
server.db.us=root
server.db.pw=
server.db.maxactive=99999

##config server
server.sv=1
server.port=14445
server.sv1=Nro:192.168.2.23:14445:0,0,0

server.waitlogin=5
server.maxperip=5
server.maxplayer=10000
server.expserver=1
server.debug=false
server.name=Hashirama
server.domain=https://nrohashirama.online/

api.port=8080
api.key=abcdefJKLMNOPQR@STUVWXYrstuv@wABCDEF@GZabxyz

#hikariCP
server.hikari.minIdle=5
server.hikari.poolSize=200
server.hikari.cachePre=true
server.hikari.cacheSize=250
server.hikari.cacheSqlLimit=2048

execute.command=java -jar target/VIP-1.0-RELEASE-jar-with-dependencies.jar

server.event=6
##config server 1 = halloween, 2 = 20/11 nha giao , 3 noel, 4 tet, 5 sk8/3
